name: Deploy React Frontend to Azure Web App

on:
  push:
    branches:
      - main
    paths:
      - 'client/**'  # Trigger only when client folder changes

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Install dependencies
        run: npm install

      - name: Build frontend
        run: npm run build

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: micromatch  # Replace with your Azure Web App name
          publish-profile: ${{ secrets.AZURE_WEBAPP_DEPLOYMENT_TOKEN }}
          package: './client/build'
