name: Deploy Node.js backend to Azure Web App

on:
  push:
    branches:
      - main # or your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 'lts/*'  # Automatically uses the latest LTS

    - name: Install dependencies
      run: |
        cd backend
        npm install

    - name: Build (if needed)
      run: |
        echo "No build step required for backend"

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: micromatch-backend             # ⬅️ Replace this with your Azure App Service name
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./backend
